version: '3.8'

networks: 
  bubble:
    external: true

services:

  function.ees.dev:
    container_name: function.ees.dev
    image: maven:3-adoptopenjdk-11-openj9
    working_dir: /app
    env_file: .env
    networks:
      - bubble
    ports:
      - "8080:8080"
    volumes:
      - $PWD/function:/app
      - ~/.m2:/root/.m2
    entrypoint: mvn com.google.cloud.functions:function-maven-plugin:0.9.4:run -Drun.functionTarget=br.com.ees.function.ContactFormFunction
